### ISSUE TITLE
我可以用你的代码在我的论文里吗？

### ISSUE THREAD

**Issue by Destaq** [JIANGFS/CVRP-Simulated-Annealing-Algorithm#1]
我是一名对模拟退火法感兴趣的高中生。今年，我老师要求我们写一篇很长关于某件有趣是的论文。他说这篇文章应该很专业，我们应该正确地引用代码等等。但是矛盾来了，您的这个项目没有任何许可证，所以我暂时无法用它。不过只要我得到允许，就没问题。我可以用您的代码在我的分析中吗？

**Comment by AaronBUAA** [comment]
当然可以的，希望能够帮到你。如果可能的话，希望能够在你公开发表论文后，给我发送一份链接，我很愿意读一读你的相关研究。

**Comment by Destaq** [comment]
感激不尽！论文是用英文写的，但是如果你还对它还有兴趣的话，我当然会把链接分享给你。

**Comment by AaronBUAA** [comment]
可以的，如果你在发表后还记得这件事情，可以给我分享一下链接~

**Comment by Destaq** [comment]
好的！

我还有一个小问题，这个是关于代码的。

```
    while T > T_end:  # 模拟退火直到温度小于终止温度
        for i in range(K):
            new_path = new_paths(old_path)  # 生成新路径
            old_path, path_dis = metropolis(old_path, new_path, node_w, m, T, D)  # 通过metropolis准则判断当前最优路径

            if path_dis <= shortest_dis:  # 如果最优路径比之前计算的结果更好，就接受
                shortest_dis = path_dis
                best_path = old_path

        dis_T[n] = shortest_dis  # 每次循环下的最优解
        n += 1
        T *= T_down_rate  # 每次循环后，以一定的下降速率降温
        print('best_dis', shortest_dis)  # 将执行过程print出来，可以时刻监控T值和当前的最优距
```

这里的while...for看起来有点不对。

<img width="617" alt="image" src="https://user-images.githubusercontent.com/61620873/168487887-5efcd62e-c402-4a2d-a72a-cef4b821e397.png">

如果我们看一下自由的百科全书或其他网站的伪代码，它通常用 "while"、"for "或两者的组合（e.x. `while T > T_end or generation < K`)。但是你while循环内还有一个循环，虽然产生的结果好得多，但似乎不是真正的simulated annealing呢。

能否请你澄清一下？有可能我看错了。

**Comment by Destaq** [comment]
哟，眼花啦。不打扰了。

**Comment by Destaq** [comment]
好嘞！我拿到了最好的分数～

@AlfredJiangBUAA 请看：[essay.pdf](https://github.com/AlfredJiangBUAA/CVRP-Simulated-Annealing-Algorithm/files/11973329/essay.pdf)

**Comment by AaronBUAA** [comment]
恭喜恭喜，替你感到高兴！！
